### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by habmin** [hobg0blin/dataville#110]

**Comment by hobg0blin** [comment]
@habmin I added MPL (seemed like the best middle-of-the-road open source option) for code and creative commons noncommercial for assets on Itch. Let me know if you have opinions about this, I am not a lawyer.

**Comment by habmin** [comment]
I couldn't even tell you what MLP is without googling it. Whatever you're
fine with I'm good, just figured we'd do it.

**Comment by hobg0blin** [comment]
Cool, if it turns out to be an issue we can change the license but for now I think this is fine.
