### ISSUE TITLE
occasional blank messages appearing after tasks

### ISSUE THREAD

**Issue by hobg0blin** [hobg0blin/dataville#30]
Assuming this is some weird line parsing thing where it's trimming the first line? Need to debug a bit.

**Comment by habmin** [comment]
lets make a note of where this specifically happens

**Comment by habmin** [comment]
When you say blank messages appearing, do you mean cogni or email message appearing with the bubble or frame, but no text? or just completely blank screens?

**Comment by hobg0blin** [comment]
> When you say blank messages appearing, do you mean cogni or email message appearing with the bubble or frame, but no text? or just completely blank screens?

I mean message appearing with bubble/frame but no text. Caught this today on the day 2 "label this as an alien" task from Alex. Will investigate shortly

**Comment by hobg0blin** [comment]
this *should* be resolved but not closing it until i've tested a bit more to make sure
